### ISSUE TITLE
how to evalutate the generated mlir file?

### ISSUE THREAD

**Issue by syheliel** [opencompl/mlir-fuzz#5]
`run_xdsl_tv.py` seems to be the file for eval. It uses a binary named `xdsl_tv`, but I can't find `xdsl_tv` in `xdsm-smt`'s repo. Would you like to add some doc about the evaluation process?

**Comment by math-fehr** [comment]
`xdsl-tv` is created with `pip install .` in the `xdsl-smt` repository.
I use `run_xdsl_tv.py` to check that if the compiled programs have bugs or not, but people might want to use other scripts.
I am not sure yet if I want to keep `run_xdsl_tv.py` in the repository, but for now it's probably better to add documentation, yes! I can do it today or tomorrow if you'd like!

**Comment by syheliel** [comment]
@math-fehr Thanks for your time！ It would be great to have a guide for xdsl's setup.

**Comment by math-fehr** [comment]
Very sorry for the delay, I got into multiple things and forgot about it!
I added a comment there, if that works for you I'll close the issue!

**Comment by syheliel** [comment]
thanks, It works for me now :)
